---
# roles/kiosk-user/handlers/main.yml

- name: Reload systemd and restart getty@tty1
  block:
    - name: systemctl daemon-reload
      ansible.builtin.systemd:
        daemon_reload: true
    - name: Restart getty@tty1
      ansible.builtin.systemd:
        name: getty@tty1.service
        state: restarted

- name: Reload sshd
  ansible.builtin.systemd:
    name: ssh.service
    state: reloaded
